# Week 2 - Day 3: Linear Algebra for Machine Learning

## Objective

Learn how vectors, matrices, dot products, and matrix multiplication are used in machine learning.

In [1]:
import numpy as np

In [2]:
customer = np.array([25, 50000, 3])

print(customer)
print("Shape:", customer.shape)

[   25 50000     3]
Shape: (3,)


In [3]:
X = np.array([
    [25, 50000, 3],
    [40, 80000, 10],
    [33, 62000, 5]
])

print(X)
print("Shape:", X.shape)

[[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]
Shape: (3, 3)


## Vectors and Matrices

A vector represents one data sample with its features.

A matrix represents multiple data samples, where each row is a sample and each column is a feature.

In [4]:
weights = np.array([0.1, 0.0002, 1.5])

print(weights)

[1.0e-01 2.0e-04 1.5e+00]


In [5]:
prediction = np.dot(customer, weights)

print("Prediction:", prediction)

Prediction: 17.0


## Dot Product

The dot product multiplies each feature by its corresponding weight and sums the results.

For this customer:

- Age contribution = 25 × 0.1 = 2.5
- Income contribution = 50000 × 0.0002 = 10
- Tenure contribution = 3 × 1.5 = 4.5

Final prediction = **17.0**

This operation is the foundation of many machine learning models such as Linear Regression and Logistic Regression.

In [6]:
predictions = X @ weights

print("Predictions:")
print(predictions)

Predictions:
[17.  35.  23.2]


## Matrix Multiplication

Matrix multiplication allows us to compute predictions for multiple samples at once.

Instead of calculating the dot product for each sample separately, we multiply the entire dataset by the weight vector, producing one prediction for each row.

In [7]:
wrong_weights = np.array([0.1, 0.0002])

X @ wrong_weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## Shape Mismatch

The error occurs because the matrix and the weight vector have incompatible shapes.

- Matrix shape: (3, 3)
- Weight vector shape: (2,)

Matrix multiplication requires the number of columns in the matrix to match the number of elements in the weight vector.

To fix the error, the weight vector must contain three values, one for each feature.

# Summary

In this notebook, we learned:

- How to represent one sample as a vector.
- How to represent a dataset as a matrix.
- How to calculate predictions using the dot product.
- How matrix multiplication generates predictions for multiple samples.
- Why matching matrix dimensions is essential for successful matrix multiplication.

These operations are fundamental building blocks for many machine learning algorithms.