# Day 1 - Environment Setup

My first AI & ML environment setup.

In [ ]:
import numpy
import pandas
import matplotlib

print("NumPy:", numpy.__version__)
print("Pandas:", pandas.__version__)
print("Matplotlib:", matplotlib.__version__)


NumPy: 2.5.1
Pandas: 3.0.3
Matplotlib: 3.11.1


# Day 2 - Python Fundamentals

## Objective
This notebook reviews the core Python concepts required for AI & Machine Learning, including data types, control flow, functions, list comprehensions, and basic object-oriented programming.

In [3]:
age = 20

height = 160

name = "Deema"

is_student = True

grades = [98,99,96]

point = (3, 4)

student = {
    "name": "Deema",
    "major": "Computer Science"
}

unique_numbers = {1, 2, 2, 3, 4}

print(type(age))
print(type(height))
print(type(name))
print(type(is_student))
print(type(grades))
print(type(point))
print(type(student))
print(type(unique_numbers))

<class 'int'>
<class 'int'>
<class 'str'>
<class 'bool'>
<class 'list'>
<class 'tuple'>
<class 'dict'>
<class 'set'>


## Control Flow

Control flow allows Python to make decisions and repeat tasks using conditions and loops.

In [5]:
score = 98
if score >= 60:
    print ("Pass, What A LEGEND!!")
else:
    print ("fail")

Pass, What A LEGEND!!


In [8]:
score = 66
if score >= 90:
    print("PERFECT!!")
elif score >= 80:
    print("Very Good")
elif score >= 70:
    print("It's fine, Go to cry")
else:
    print("NO NO NO, Not Good!!!!!")
    

NO NO NO, Not Good!!!!!


In [9]:
Numbers = [100,90,80,70,60,19]
for number in Numbers:
    print(number)

100
90
80
70
60
19


In [12]:
count = 1
while count <= 5:
    print(count)
    print("You can cry Messi")
    count += 1

1
You can cry Messi
2
You can cry Messi
3
You can cry Messi
4
You can cry Messi
5
You can cry Messi


In [3]:
Num = 1

while Num <= 10:
    print(Num)

    if Num % 2 == 0:
        print("Number is Even")
    else:
        print("Number is Odd")

    Num += 1

1
Number is Odd
2
Number is Even
3
Number is Odd
4
Number is Even
5
Number is Odd
6
Number is Even
7
Number is Odd
8
Number is Even
9
Number is Odd
10
Number is Even


In [8]:
for num in range(1,20):
    if num%2 == 0:
        print (f"{num} is even")
    else:
        print(f"{num} is odd")
        

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
10 is even
11 is odd
12 is even
13 is odd
14 is even
15 is odd
16 is even
17 is odd
18 is even
19 is odd


## Functions

Functions allow us to write reusable code. Instead of repeating the same logic multiple times, we define it once and call it whenever needed.

In [11]:
def Spain(Loser):
    print("The Winner Takes It All!", Loser)

Spain("Congratulation SPAIN!!")   
Spain("1 - 0")   



The Winner Takes It All! Congratulation SPAIN!!
The Winner Takes It All! 1 - 0


In [12]:
def Normalize(Value, Min_Value, Max_Value):
    return (Value - Min_Value)/(Max_Value - Min_Value)
print (Normalize(90,100,60))   
    

0.25


In [13]:
def avg(f_mark, se_mark, th_mark, ft_mark, num_of_marks):
    return (f_mark + se_mark + th_mark + ft_mark)/ (num_of_marks)
print (avg(90,96,95,97,4))    

94.5


## Array Attributes

NumPy arrays have useful attributes such as shape, data type (dtype), and number of dimensions (ndim).


In [1]:
import numpy as np
m = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Shape:", m.shape)
print("Data Type:", m.dtype)
print("Dimensions:", m.ndim)
print("Size:", m.size)

Shape: (2, 3)
Data Type: int64
Dimensions: 2
Size: 6


In [6]:
import numpy as np
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[1, 1])

50


## Vectorized Operations

NumPy performs mathematical operations on entire arrays without using loops. This makes the code faster and easier to read.

In [7]:
a = np.array([1, 2, 3, 4])

print("Original:", a)
print("Multiply by 2:", a * 2)
print("Add itself:", a + a)
print("Mean:", a.mean())

Original: [1 2 3 4]
Multiply by 2: [2 4 6 8]
Add itself: [2 4 6 8]
Mean: 2.5


## Boolean Masking

Boolean masking filters array elements based on a condition.

In [13]:
a = np.array([1, 9, 3, 4, 0 ])

print(a > 2)
print(a[a>2])

[False  True  True  True False]
[9 3 4]


## Broadcasting

Broadcasting allows NumPy to perform operations between arrays of compatible shapes.

In [14]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

row = np.array([10, 20, 30])

print(matrix + row)

[[11 22 33]
 [14 25 36]]


# Hands-On Lab

In this lab, we practice creating NumPy arrays, slicing, boolean masking, and broadcasting.

In [15]:
array = np.arange(1, 17).reshape(4, 4)

print(array)
print("Shape:", array.shape)
print("Data Type:", array.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)
Data Type: int64


## Step 2: Array Slicing

Extract the second column and the last row using slicing.

In [16]:
print("Second Column:")
print(array[:, 1])

print("Last Row:")
print(array[3, :])

Second Column:
[ 2  6 10 14]
Last Row:
[13 14 15 16]


## Step 3: Boolean Masking

Select all values greater than the mean of the array.

In [17]:
mean = array.mean()

print("Mean:", mean)

print(array[array > mean])

Mean: 8.5
[ 9 10 11 12 13 14 15 16]


## Step 4: Broadcasting

Add a one-dimensional row array to every row of the matrix.